"""init

Revision ID: 0e2d1d7fc3cb
Revises: 
Create Date: 2023-10-08 15:01:13.157693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e2d1d7fc3cb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "media_type",
            sa.Enum("image", "video", "document", name="media_type"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("storage_id", sa.UUID(), nullable=False),
        sa.Column("file_identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "storage_id", "file_identifier", name="unique_identifier"
        ),
    )
    op.create_index(
        op.f("ix_media_file_identifier"),
        "media",
        ["file_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_media_type"), "media", ["media_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_owner_id"), "media", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_storage_id"), "media", ["storage_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_storage_id"), table_name="media")
    op.drop_index(op.f("ix_media_owner_id"), table_name="media")
    op.drop_index(op.f("ix_media_media_type"), table_name="media")
    op.drop_index(op.f("ix_media_file_identifier"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
