"""media_ack

Revision ID: 52f15221fa1e
Revises: 0e2d1d7fc3cb
Create Date: 2023-12-21 15:31:44.888701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52f15221fa1e"
down_revision: Union[str, None] = "0e2d1d7fc3cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column("ack", sa.Boolean(), server_default="true", nullable=False),
    )
    op.alter_column("media", "ack", server_default=None)
    op.create_index(op.f("ix_media_ack"), "media", ["ack"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_ack"), table_name="media")
    op.drop_column("media", "ack")
    # ### end Alembic commands ###
