"""user_created_ack_at

Revision ID: 790bcd7683f6
Revises: 52f15221fa1e
Create Date: 2024-09-28 00:24:39.571914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "790bcd7683f6"
down_revision: Union[str, None] = "52f15221fa1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("media", sa.Column("ack_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE media SET ack_at = CURRENT_TIMESTAMP WHERE ack = TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "ack_at")
    op.drop_column("media", "created_at")
    # ### end Alembic commands ###
